import { useMemo } from 'react'
import { Activity, CalendarClock, Database, ShieldCheck } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { formatRelativeExpiry } from '@/lib/dateFormatter'
import type { UserInfo } from '@/types/user'
import { CyberCard, SectionHeading } from './CyberCard'
const bytes=(value:number)=>{if(!value||value<=0)return '0 B';const units=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return `${(value/Math.pow(1024,i)).toFixed(2)} ${units[i]}`}
export function AccountOverview({user}:{user:UserInfo}){
 const {t}=useTranslation(); const status=String(user.status).toLowerCase()
 const expiry=useMemo(()=>status==='on_hold'?(user.on_hold_expire_duration?`${Math.floor(user.on_hold_expire_duration/86400)} ${t('time.days')}`:t('userInfo.noTimeLimit')):formatRelativeExpiry(user.expire,t).time,[status,user.expire,user.on_hold_expire_duration,t])
 const used=user.used_traffic||0, limit=user.data_limit||0, percent=limit>0?Math.min(used/limit*100,100):0
 const statusClass=status==='active'?'status-active':status==='limited'||status==='expired'?'status-danger':status==='on_hold'?'status-hold':'status-muted'
 const metrics=[{icon:Database,label:t('userInfo.usedTraffic'),value:bytes(used)},{icon:Activity,label:t('remaining'),value:limit>0?bytes(Math.max(limit-used,0)):t('userInfo.unlimited')},{icon:CalendarClock,label:t('userInfo.expiryDate'),value:expiry}]
 return <CyberCard id="overview" className="overflow-hidden"><div className="p-5 sm:p-7"><SectionHeading eyebrow="ACCOUNT INTELLIGENCE" title={t('userInfo.title')}/><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="relative rounded-2xl border border-border/70 bg-background/35 p-5 sm:p-6 overflow-hidden"><div className="absolute inset-0 pointer-events-none cyber-scanline"/><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="cyber-eyebrow">{t('userInfo.username')}</div><div dir="ltr" className="mt-2 truncate text-2xl sm:text-3xl font-semibold tracking-tight text-start">{user.username}</div></div><div className={`cyber-status ${statusClass}`}><span className="cyber-dot"/>{t(`status.${status}`)}</div></div><div className="mt-8 flex items-center gap-5"><div className="relative h-28 w-28 shrink-0"><svg viewBox="0 0 120 120" className="h-full w-full -rotate-90"><circle cx="60" cy="60" r="50" fill="none" stroke="currentColor" strokeWidth="8" className="text-muted/20"/><circle cx="60" cy="60" r="50" fill="none" stroke="currentColor" strokeWidth="8" strokeLinecap="round" className={statusClass==='status-danger'?'text-destructive':'text-primary'} strokeDasharray={314} strokeDashoffset={314-(314*percent/100)}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><b className="text-2xl">{percent.toFixed(0)}%</b><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{t('userInfo.used')}</span></div></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3 text-sm"><span className="text-muted-foreground">{t('userInfo.usedTraffic')}</span><b dir="ltr">{bytes(used)}</b></div><div className="mt-2 h-1.5 rounded-full bg-muted overflow-hidden"><div className="h-full rounded-full bg-primary transition-[width] duration-700" style={{width:`${percent}%`}}/></div><div className="mt-3 flex justify-between gap-3 text-xs text-muted-foreground"><span>{t('userInfo.totalLimit')}</span><span dir="ltr">{limit>0?bytes(limit):t('userInfo.unlimited')}</span></div></div></div></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{metrics.map(({icon:Icon,label,value})=><div key={label} className="cyber-metric"><Icon className="h-4 w-4 text-primary"/><div className="min-w-0"><div className="cyber-eyebrow">{label}</div><div dir="ltr" className="mt-1 truncate text-lg font-semibold text-start">{value}</div></div></div>)}<div className="cyber-metric"><ShieldCheck className="h-4 w-4 text-secondary"/><div><div className="cyber-eyebrow">{t('online')}</div><div className="mt-1 text-sm font-medium">{user.online_at?new Date(user.online_at).toLocaleString():t('notConnectedYet')}</div></div></div></div></div></div></CyberCard>
}
