import { useMemo,useState } from 'react'
import { ChevronDown, Check, Download, ScanQrCode } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { parseLink,type ParsedLink } from '@/lib/linkParser'
import { getWireGuardDownloadPayload,downloadTextFile,prepareSubscriptionContentForCopy } from '@/lib/subscriptionConfig'
import { useCopyToClipboard } from '@/hooks/useCopyToClipboard'
import { QRModal } from '@/components/qr-modal'
import { CyberCard } from './CyberCard'
const protocolLabel=(p:ParsedLink['protocol'])=>p==='wireguard'?'AMNEZIA WG':p==='hysteria'?'HY2':p==='shadowsocks'?'SHADOWSOCKS':p.toUpperCase()
export function ConfigCard({link,index}:{link:string;index:number}){
 const {t}=useTranslation();const parsed=useMemo(()=>parseLink(link,index),[link,index]);const {copyToClipboard,isCopied}=useCopyToClipboard();const [details,setDetails]=useState(false);const [qr,setQr]=useState(false);const wg=useMemo(()=>getWireGuardDownloadPayload(parsed.raw),[parsed.raw])
 const advanced=useMemo(()=>{if(parsed.protocol!=='wireguard')return [];try{const u=new URL(parsed.raw);const keys=['jc','jmin','jmax','s1','s2','s3','s4','h1','h2','h3','h4','h5','i1','i2','i3','i4','i5','mtu','dns','reserved','keepalive'];return keys.map(k=>[k,u.searchParams.get(k)] as const).filter((x):x is [string,string]=>Boolean(x[1]))}catch{return []}},[parsed])
 const copy=()=>{const prepared=prepareSubscriptionContentForCopy(parsed.raw);copyToClipboard(prepared.content,`${parsed.raw}:config`)}
 const download=()=>{if(!wg)return;downloadTextFile(wg.content,wg.fileName);toast.success(t('configActions.downloadStarted'))}
 const copied=isCopied(`${parsed.raw}:config`)
 return <CyberCard className="p-4 sm:p-5"><div className="flex items-start gap-3"><div className="cyber-protocol">{protocolLabel(parsed.protocol)}</div><div className="min-w-0 flex-1"><div dir="ltr" className="truncate text-sm font-semibold text-start">{parsed.name}</div><div dir="ltr" className="mt-1 truncate text-xs text-muted-foreground text-start">{parsed.server||'—'}{parsed.port?`:${parsed.port}`:''}</div></div><button className="icon-action" onClick={()=>setDetails(v=>!v)} aria-label={t('apps.viewDetails')} title={t('apps.viewDetails')}><ChevronDown className={`h-4 w-4 transition-transform ${details?'rotate-180':''}`}/></button></div>{details&&<div className="mt-4 border-t border-border/60 pt-4 space-y-3 text-xs"><div className="grid grid-cols-2 gap-2"><span className="text-muted-foreground">Protocol</span><b>{protocolLabel(parsed.protocol)}</b><span className="text-muted-foreground">Server</span><b dir="ltr" className="text-start truncate">{parsed.server||'—'}</b><span className="text-muted-foreground">Port</span><b dir="ltr" className="text-start">{parsed.port||'—'}</b></div>{advanced.length>0&&<div><div className="cyber-eyebrow mb-2">ADVANCED PARAMETERS</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{advanced.map(([k,v])=><div key={k} className="rounded-lg border border-border/60 bg-background/40 p-2"><span className="text-muted-foreground">{k}</span><div dir="ltr" className="mt-1 truncate font-mono text-[11px] text-start">{v}</div></div>)}</div></div>}<details><summary className="cursor-pointer text-muted-foreground hover:text-foreground">{t('configActions.copyConfig')}</summary><pre dir="ltr" className="mt-2 max-h-32 overflow-auto rounded-lg bg-black/30 p-3 text-[10px] leading-4 text-start">{parsed.raw}</pre></details></div>}<div className="mt-4 flex flex-wrap gap-2"><button className={`cyber-action-primary ${copied?'is-success':''}`} onClick={copy}>{copied?<Check className="h-3.5 w-3.5"/>:null}{copied?t('qr.copied'):t('configActions.copyConfig')}</button>{wg&&<button className="cyber-action" onClick={download}><Download className="h-3.5 w-3.5"/>{t('configActions.downloadWireGuard')}</button>}<button className="cyber-action" onClick={()=>setQr(true)}><ScanQrCode className="h-3.5 w-3.5"/>{t('qr.show')}</button></div><QRModal link={parsed} open={qr} onOpenChange={setQr}/></CyberCard>
}
