import { useMemo,useState } from 'react'
import { Copy,ExternalLink,Files,Link2,Network,QrCode,Shield } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { parseLinks,type ParsedLink } from '@/lib/linkParser'
import { QRModal } from '@/components/qr-modal'
import { useCopyToClipboard } from '@/hooks/useCopyToClipboard'
import { prepareSubscriptionContentForCopy } from '@/lib/subscriptionConfig'
import { CyberCard,SectionHeading } from './CyberCard'
import { ConfigCard } from './ConfigCard'
export function ConnectionCenter({links}:{links:string[]}){
 const {t}=useTranslation();const {copyToClipboard}=useCopyToClipboard();const [tab,setTab]=useState<'all'|'xray'|'wg'>('all');const [qr,setQr]=useState(false);const parsed=useMemo(()=>parseLinks(links),[links]);const xray=parsed.filter(x=>x.protocol!=='wireguard');const wg=parsed.filter(x=>x.protocol==='wireguard');const subscriptionUrl=useMemo(()=>window.location.origin+window.location.pathname.replace(/\/info$/,''),[]);const visible=tab==='xray'?xray:tab==='wg'?wg:parsed
 const copyAll=()=>{const raw=parsed.map(x=>x.raw).join('\n');copyToClipboard(prepareSubscriptionContentForCopy(raw).content,raw);toast.success(t('apps.copyAllSuccess'))};const sub:ParsedLink={protocol:'unknown',name:t('config.subscriptionLink'),emoji:'📱',raw:subscriptionUrl}
 return <div id="connections" className="space-y-5"><CyberCard className="p-5 sm:p-7"><SectionHeading eyebrow={t('portal.connectionCenter')} title={t('config.title')} meta={`${parsed.length} ${t('portal.configurations')}`} action={<button className="cyber-action-primary" onClick={copyAll}><Files className="h-4 w-4"/>{t('apps.copyAll')}</button>}/><div className="cyber-subscription"><div className="flex min-w-0 items-center gap-3"><div className="cyber-icon"><Link2 className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="cyber-eyebrow">{t('config.subscriptionLink')}</div><div dir="ltr" className="mt-1 truncate text-xs text-muted-foreground text-start">{subscriptionUrl}</div></div></div><div className="flex gap-2"><button className="icon-action" onClick={()=>copyToClipboard(subscriptionUrl,subscriptionUrl)} title={t('qr.copy')}><Copy className="h-4 w-4"/></button><button className="icon-action" onClick={()=>setQr(true)} title={t('qr.show')}><QrCode className="h-4 w-4"/></button><a className="icon-action" href={subscriptionUrl} target="_blank" rel="noreferrer" title="Open"><ExternalLink className="h-4 w-4"/></a></div></div><div className="mt-5 grid grid-cols-3 gap-2 rounded-xl border border-border/60 bg-background/30 p-1"><button className={tab==='all'?'cyber-tab-active':'cyber-tab'} onClick={()=>setTab('all')}><Network className="h-3.5 w-3.5"/>{t('portal.all')}</button><button className={tab==='xray'?'cyber-tab-active':'cyber-tab'} onClick={()=>setTab('xray')}><Shield className="h-3.5 w-3.5"/>{t('portal.xrayProxy')}<span>{xray.length}</span></button><button className={tab==='wg'?'cyber-tab-active':'cyber-tab'} onClick={()=>setTab('wg')}><Network className="h-3.5 w-3.5"/>{t('portal.amneziaWG')}<span>{wg.length}</span></button></div>{visible.length?<div className="mt-5 grid gap-3 lg:grid-cols-2">{visible.map(item=><ConfigCard key={item.raw} link={item.raw} index={parsed.indexOf(item)}/>)}</div>:<div className="empty-state">{t('portal.noConfigurations')}</div>}<QRModal link={sub} open={qr} onOpenChange={setQr}/></CyberCard></div>
}
